default: &default
  SMTP_ADDRESS: 'smtp.gmail.com'
  SMTP_PORT: '465'
  SMTP_USER_NAME: '<your_email_address>'
  SMTP_PASSWORD: '<your_email_password>'

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
